apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-frontend
  template:
    metadata:
      labels:
        app: travel-frontend
    spec:
      containers:
        - name: travel-frontend
          image: gj2300031720/travel-frontend:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: travel-frontend-service
spec:
  selector:
    app: travel-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
